import { pageRoutes } from "./routes";
import { UserRoles } from "./types";

export const RolesForSection: {
  [key in keyof typeof pageRoutes]: Record<UserRoles, boolean>;
} = {
  home: {
    [UserRoles.NONE]: true,
    [UserRoles.ADMIN]: true,
    [UserRoles.BUYER]: true,
    [UserRoles.LEGAL]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.SELLER_BUYER]: true,
  },
  search: {
    [UserRoles.ADMIN]: true,
    [UserRoles.BUYER]: true,
    [UserRoles.LEGAL]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.NONE]: false,
  },
  myRequirements: {
    [UserRoles.ADMIN]: true,
    [UserRoles.BUYER]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.NONE]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.LEGAL]: false,
  },
  myOffers: {
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.NONE]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
  myPurchaseOrders: {
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.NONE]: false,
    [UserRoles.BUYER]: true,
    [UserRoles.LEGAL]: false,
  },
  users: {
    [UserRoles.ADMIN]: true,
    [UserRoles.NONE]: false,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
  profile: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.BUYER]: true,
    [UserRoles.LEGAL]: true,
  },
  chat: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: true,
    [UserRoles.SELLER]: true,
    [UserRoles.BUYER]: true,
    [UserRoles.LEGAL]: true,
  },
  allRequirements: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
  allOffers: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
  certificates: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: true,
  },
  allPurchaseOrders: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
  statistics: {
    [UserRoles.NONE]: false,
    [UserRoles.ADMIN]: true,
    [UserRoles.SELLER_BUYER]: false,
    [UserRoles.SELLER]: false,
    [UserRoles.BUYER]: false,
    [UserRoles.LEGAL]: false,
  },
};
