import { useTranslation } from "react-i18next";
import TablePageContent from "../components/section/table-page/TablePageContent";
import { ChangeEvent, useState } from "react";
import { TableTypeAllRequirements } from "../models/Interfaces";
import {
  Action,
  EntityType,
  RequirementState,
  RequirementType,
  TableTypes,
} from "../utilities/types";
import { BasicRequirement, Requirement } from "../models/MainInterfaces";

const requirements: Requirement[] = [
  {
    key: "1",
    title: "Liquido 10 Unidades de Teléfono inteligente Samsung Galaxy S20",
    category: 1,
    coin: 1,
    price: 5500,
    numberOffers: 999,
    state: RequirementState.CANCELED,
    type: RequirementType.GOOD,
    location: 2,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    deliveryTime: 1,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lobortis convallis metus a faucibus. Phasellus tristique nec lorem a vulputate. Morbi varius volutpat orci, in viverra risus venenatis sit amet. Duis convallis nisi nec ligula luctus, in elementum orci ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec quam ante, aliquam rhoncus sollicitudin a, lacinia vitae odio. Aenean quis facilisis augue. Donec iaculis aliquam odio, nec fermentum lectus eleifend ac. Sed fermentum nisl eu aliquet pulvinar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar elit ac volutpat elementum. Donec interdum id turpis ac ultrices. Vivamus et nunc iaculis, suscipit libero nec, lobortis ex. Vestibulum vitae gravida tortor, eleifend placerat mi. Integer mauris nunc, elementum et dui non, posuere malesuada erat. Aliquam semper aliquet interdum.",
    image: [
      "https://imgv3.fotor.com/images/cover-photo-image/AI-illustration-of-a-dragon-by-Fotor-AI-text-to-image-generator.jpg",
    ],
    user: {
      uid: "user1",
      name: "Soluciones Online Soluciones Online Soluciones Online S. A. C.",
      email: "john.doejohn.doejohn.doejohn.doe@example.com",

      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 3,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "9898989",
      customerCount: 0,
      sellerCount: 0,
    },
    subUser: {
      uid: "subuser1",
      name: "Javier Req Solís Calcina Javier Alberto Solís Calcina",
      email: "javiersolis@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",
      phone: "998989898",

      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "2",
    title:
      "Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas. Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas",
    category: 2,
    coin: 2,
    price: 234,
    numberOffers: 0,
    state: RequirementState.EXPIRED,
    type: RequirementType.GOOD,
    location: 4,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 2,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 2,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "22222222",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "3",
    title:
      "Se requiere un ordenador portátil resistente para uso en exteriores",
    category: 3,
    coin: 1,
    price: 230,
    numberOffers: 0,
    state: RequirementState.DISPUTE,
    type: RequirementType.GOOD,
    location: 6,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 3,
    user: {
      uid: "user1",
      name: "Soluciones Online Soluciones Online Soluciones Online S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 1,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "44444444",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "4",
    title: "Necesito 10 Monitores de PC con Variedad en Marca y Tamaño",
    category: 4,
    coin: 1,
    price: 2323,
    numberOffers: 3,
    state: RequirementState.FINISHED,
    type: RequirementType.GOOD,
    location: 10,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 4,
    user: {
      uid: "user1",
      name: "Soluciones Online Soluciones Online Soluciones Online S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 5,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "54533133",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "5",
    title: "Requiero 15 Escritorios de Oficina con Variedad en Marca y Color",
    category: 5,
    coin: 2,
    price: 455,
    numberOffers: 0,
    state: RequirementState.PUBLISHED,
    type: RequirementType.GOOD,
    location: 7,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 5,
    user: {
      uid: "user2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      document: "987654321",
      tenure: 15,
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "543434242",
      customerCount: 0,
      sellerCount: 0,
    },
    subUser: {
      uid: "subuser1",
      name: "Javier Req Solís Calcina Javier Alberto Solís Calcina",
      email: "javiersolis@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",
      phone: "998989898",

      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "6",
    title: "Se requiere comprar muebles para la sala de espera",
    category: 6,
    coin: 2,
    price: 500,
    numberOffers: 1,
    state: RequirementState.SELECTED,
    type: RequirementType.GOOD,
    location: 5,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 6,
    user: {
      uid: "user2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      document: "987654321",
      tenure: 24,
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "1233133213",
      customerCount: 0,
      sellerCount: 0,
    },
    subUser: {
      uid: "subuser1",
      name: "Javier Req Solís Calcina Javier Alberto Solís Calcina",
      email: "javiersolis@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",
      phone: "998989898",

      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "7",
    title: "Liquido 10 Unidades de Teléfono inteligente Samsung Galaxy S20",
    category: 7,
    coin: 1,
    price: 5500,
    numberOffers: 999,
    state: RequirementState.CANCELED,
    type: RequirementType.GOOD,
    location: 11,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    deliveryTime: 6,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lobortis convallis metus a faucibus. Phasellus tristique nec lorem a vulputate. Morbi varius volutpat orci, in viverra risus venenatis sit amet. Duis convallis nisi nec ligula luctus, in elementum orci ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec quam ante, aliquam rhoncus sollicitudin a, lacinia vitae odio. Aenean quis facilisis augue. Donec iaculis aliquam odio, nec fermentum lectus eleifend ac. Sed fermentum nisl eu aliquet pulvinar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar elit ac volutpat elementum. Donec interdum id turpis ac ultrices. Vivamus et nunc iaculis, suscipit libero nec, lobortis ex. Vestibulum vitae gravida tortor, eleifend placerat mi. Integer mauris nunc, elementum et dui non, posuere malesuada erat. Aliquam semper aliquet interdum.",
    image: [
      "https://imgv3.fotor.com/images/cover-photo-image/AI-illustration-of-a-dragon-by-Fotor-AI-text-to-image-generator.jpg",
    ],
    user: {
      uid: "user1",
      name: "Soluciones Online Soluciones Online Soluciones Online S. A. C.",
      email: "john.doejohn.doejohn.doejohn.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 2,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "44454435",
      customerCount: 0,
      sellerCount: 0,
    },
    subUser: {
      uid: "subuser1",
      name: "Javier Req Solís Calcina Javier Alberto Solís Calcina",
      email: "javiersolis@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "123231",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "8",
    title:
      "Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas. Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas",
    category: 8,
    coin: 2,
    price: 234,
    numberOffers: 0,
    state: RequirementState.EXPIRED,
    type: RequirementType.GOOD,
    location: 12,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 6,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "9",
    title:
      "Se requiere un ordenador portátil resistente para uso en exteriores",
    category: 9,
    coin: 1,
    price: 230,
    numberOffers: 0,
    state: RequirementState.DISPUTE,
    type: RequirementType.GOOD,
    location: 2,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 5,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "10",
    title: "Necesito 10 Monitores de PC con Variedad en Marca y Tamaño",
    category: 10,
    coin: 2,
    price: 2323,
    numberOffers: 3,
    state: RequirementState.FINISHED,
    type: RequirementType.GOOD,
    location: 13,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 4,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "11",
    title: "Requiero 15 Escritorios de Oficina con Variedad en Marca y Color",
    category: 11,
    coin: 2,
    price: 455,
    numberOffers: 0,
    state: RequirementState.PUBLISHED,
    type: RequirementType.GOOD,
    location: 7,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 3,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "12",
    title: "Se requiere comprar muebles para la sala de espera",
    category: 12,
    coin: 2,
    price: 500,
    numberOffers: 1,
    state: RequirementState.SELECTED,
    type: RequirementType.GOOD,
    location: 8,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 2,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "13",
    title: "Liquido 10 Unidades de Teléfono inteligente Samsung Galaxy S20",
    category: 13,
    coin: 2,
    price: 5500,
    numberOffers: 999,
    state: RequirementState.CANCELED,
    type: RequirementType.GOOD,
    location: 2,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    deliveryTime: 1,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lobortis convallis metus a faucibus. Phasellus tristique nec lorem a vulputate. Morbi varius volutpat orci, in viverra risus venenatis sit amet. Duis convallis nisi nec ligula luctus, in elementum orci ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec quam ante, aliquam rhoncus sollicitudin a, lacinia vitae odio. Aenean quis facilisis augue. Donec iaculis aliquam odio, nec fermentum lectus eleifend ac. Sed fermentum nisl eu aliquet pulvinar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar elit ac volutpat elementum. Donec interdum id turpis ac ultrices. Vivamus et nunc iaculis, suscipit libero nec, lobortis ex. Vestibulum vitae gravida tortor, eleifend placerat mi. Integer mauris nunc, elementum et dui non, posuere malesuada erat. Aliquam semper aliquet interdum.",
    image: [
      "https://imgv3.fotor.com/images/cover-photo-image/AI-illustration-of-a-dragon-by-Fotor-AI-text-to-image-generator.jpg",
    ],
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
    subUser: {
      uid: "subuser1",
      name: "Javier Req Solís Calcina Javier Alberto Solís Calcina",
      email: "javiersolis@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "1111111",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "14",
    title:
      "Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas. Se necesita un maletín ejecutivo con un compartimento acolchado para un portátil de 15 pulgadas",
    category: 14,
    coin: 2,
    price: 234,
    numberOffers: 0,
    state: RequirementState.EXPIRED,
    type: RequirementType.GOOD,
    location: 12,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 2,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "15",
    title:
      "Se requiere un ordenador portátil resistente para uso en exteriores",
    category: 15,
    coin: 2,
    price: 230,
    numberOffers: 0,
    state: RequirementState.DISPUTE,
    type: RequirementType.GOOD,
    location: 8,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 3,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "16",
    title: "Necesito 10 Monitores de PC con Variedad en Marca y Tamaño",
    category: 15,
    coin: 1,
    price: 2323,
    numberOffers: 3,
    state: RequirementState.FINISHED,
    type: RequirementType.GOOD,
    location: 9,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    deliveryTime: 6,
    description: "Desription",
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "17",
    title: "Requiero 15 Escritorios de Oficina con Variedad en Marca y Color",
    category: 6,
    coin: 1,
    price: 455,
    numberOffers: 0,
    state: RequirementState.PUBLISHED,
    type: RequirementType.GOOD,
    location: 10,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    deliveryTime: 6,
    description: "Desription",
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
  {
    key: "18",
    title: "Se requiere comprar muebles para la sala de espera",
    category: 9,
    coin: 2,
    price: 500,
    numberOffers: 1,
    state: RequirementState.SELECTED,
    type: RequirementType.GOOD,
    location: 1,
    publishDate: "2024-09-12T20:36:45.673Z",
    expirationDate: "2024-09-12T20:36:45.673Z",
    description: "Desription",
    deliveryTime: 1,
    user: {
      uid: "user1",
      name: "Soluciones Online  S. A. C.",
      email: "john.doe@example.com",
      document: "123456789",
      typeEntity: EntityType.COMPANY,
      tenure: 6,
      customerScore: 0,
      sellerScore: 0,
      address: "Calle San Agustin 107 - Cercado - Arequipa",

      phone: "894859430",
      customerCount: 0,
      sellerCount: 0,
    },
  },
];

export default function AllRequirements() {
  const { t } = useTranslation();
  const [tableContent, setTableContent] = useState<TableTypeAllRequirements>({
    type: TableTypes.ALL_REQUIREMENTS,
    data: requirements, //[]
    hiddenColumns: [],
    nameColumnHeader: t("goods"),
    onButtonClick: handleOnButtonClick,
  });

  function handleSearch(e: ChangeEvent<HTMLInputElement>) {
    console.log(e.target.value);
  }

  function handleOnButtonClick(action: Action, requirement: BasicRequirement) {
    console.log(action, requirement);
  }

  return (
    <TablePageContent
      title={t("requirements")}
      titleIcon={<i className="fa-regular fa-dolly c-default"></i>}
      subtitle={`${t("listOf")} ${t("goods")}`}
      subtitleIcon={<i className="fa-light fa-person-dolly sub-icon"></i>}
      table={tableContent}
      onSearch={handleSearch}
    />
  );
}
